# faster_rcnn_R_101_FPN_base.yaml
_BASE_: "../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False

DATASETS:
  TRAIN: ('coco_taco_train_base',)
  TEST: ('coco_taco_test_base',)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (85000, 100000)
  MAX_ITER: 110000
  CHECKPOINT_PERIOD: 10000

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/faster_rcnn_R_101_FPN_base_refined"