_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 17
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('taco_5shot_2025_train',)
  TEST: ('taco_5shot_2025_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (14400,)
  MAX_ITER: 16000
  WARMUP_ITERS: 100
  WARMUP_FACTOR: 0.001
  CHECKPOINT_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (1024, 1088, 1152, 1216, 1280)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1600
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/5shot_2025_small"