_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 17
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('taco_30shot_42_train',)
  TEST: ('taco_30shot_42_val',)
SOLVER:
  BASE_LR: 0.001
  MAX_ITER: 5000
  STEPS: (3000, 4000)
  WARMUP_ITERS: 200
  WARMUP_FACTOR: 0.001
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/30shot_42"