_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 17
    FREEZE_FEAT: True
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.25
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  ANCHOR_GENERATOR:
    SIZES: [[8], [16], [32], [64], [128, 256]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RPN:
    NMS_THRESH: 0.5
    POST_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TEST: 1000
DATASETS:
  TRAIN: ('taco_1shot_42_train',)
  TEST: ('taco_1shot_42_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (1500,)
  MAX_ITER: 4000
  WARMUP_ITERS: 100
  WARMUP_FACTOR: 0.001
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (1400, 1600, 1800)
  MAX_SIZE_TRAIN: 3000
  MIN_SIZE_TEST: 1600
  MAX_SIZE_TEST: 3000
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/1shot_42_small"