_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 17
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('taco_30shot_42_train',)
  TEST: ('taco_30shot_42_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (10000,)
  MAX_ITER: 500
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/30shot_42"