_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/scale_transfer_cigbutts/model_combined.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 16
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('taco_30shot_42_train',)
  TEST: ('taco_30shot_42_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (216000,)
  MAX_ITER: 240000
  CHECKPOINT_PERIOD: 12000
  WARMUP_ITERS: 10
OUTPUT_DIR: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/combined"