_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/scale_transfer_cigbutts/model_combined.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 16
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('taco_30shot_42_train',)
  TEST: ('taco_30shot_42_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (19000,)
  MAX_ITER: 20000
  WARMUP_ITERS: 100
  WARMUP_FACTOR: 0.001
  CHECKPOINT_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (1024, 1088, 1152, 1216, 1280)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1600
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "/content/drive/MyDrive/fsdet/checkpoints/coco_taco/faster_rcnn/model_combined"